// Generates static sample analysis results for the 3 built-in example flows.
// Run: node scripts/generate-samples.mjs
// Output: src/lib/sample-results.ts
//
// Re-run whenever EXAMPLE_FLOWS change in App.tsx or SYSTEM_PROMPT changes
// in src/lib/prompts.ts. The generated file is committed — we ship the
// pre-computed JSON so sample analyses render instantly.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, '..')

// --- Load API key from .env.local ---------------------------------------

const envFile = readFileSync(join(projectRoot, '.env.local'), 'utf8')
const apiKeyMatch = envFile.match(/VITE_ANTHROPIC_API_KEY\s*=\s*(.+?)\s*$/m)
if (!apiKeyMatch) {
  console.error('Could not find VITE_ANTHROPIC_API_KEY in .env.local')
  process.exit(1)
}
const apiKey = apiKeyMatch[1].replace(/^['"]|['"]$/g, '')

// --- Extract SYSTEM_PROMPT from the source of truth ---------------------

const promptsFile = readFileSync(join(projectRoot, 'src/lib/prompts.ts'), 'utf8')
const promptMatch = promptsFile.match(/SYSTEM_PROMPT\s*=\s*`([\s\S]+?)`/)
if (!promptMatch) {
  console.error('Could not extract SYSTEM_PROMPT from src/lib/prompts.ts')
  process.exit(1)
}
const SYSTEM_PROMPT = promptMatch[1]

// --- Sample flows (must match EXAMPLE_FLOWS in src/App.tsx) -------------

const SAMPLES = [
  {
    label: 'SaaS signup',
    text: 'User lands on pricing page, clicks Start Free Trial, enters email and password, fills out a 6 field profile form including company size and role, selects a plan, enters credit card details, lands on empty dashboard.',
  },
  {
    label: 'Mobile app',
    text: 'New user downloads the app, sees a welcome screen, taps Get Started, is asked to grant location and notification permissions, creates an account with email and password, is shown a 4 screen tutorial, lands on the home feed.',
  },
  {
    label: 'Marketplace',
    text: 'User lands on homepage, browses listings, clicks Contact Seller, is prompted to create an account, enters email and password, completes a profile with photo upload and bio, verifies phone number, can now message seller.',
  },
]

// --- Generate one analysis at a time ------------------------------------

async function analyzeOne(flowDescription) {
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2000,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: flowDescription }],
    }),
  })

  if (!response.ok) {
    throw new Error(`API ${response.status}: ${await response.text()}`)
  }

  const data = await response.json()
  const raw = data.content[0].text
  const clean = raw.replace(/```json|```/g, '').trim()
  return JSON.parse(clean)
}

// --- Main ---------------------------------------------------------------

const results = {}
for (const sample of SAMPLES) {
  process.stdout.write(`Analyzing "${sample.label}"... `)
  const t0 = Date.now()
  try {
    const result = await analyzeOne(sample.text)
    const ms = Date.now() - t0
    console.log(`done in ${(ms / 1000).toFixed(1)}s (${result.friction_points.length} friction points)`)
    results[sample.label] = result
  } catch (err) {
    console.error(`FAILED: ${err.message}`)
    process.exit(1)
  }
}

// --- Write sample-results.ts --------------------------------------------

const output = `// Auto-generated by scripts/generate-samples.mjs — do not edit by hand.
// Pre-computed analyses for the 3 built-in sample flows. Served instantly
// when a user clicks Analyze on an unmodified sample, so the demo feels
// responsive instead of paying the 20–30s LLM generation cost.
//
// Regenerate with: node scripts/generate-samples.mjs

import type { AnalysisResult } from '../types/analysis'

export const SAMPLE_FLOWS = {
${SAMPLES.map((s) => `  ${JSON.stringify(s.label)}: ${JSON.stringify(s.text)},`).join('\n')}
} as const

export const SAMPLE_RESULTS: Record<string, AnalysisResult> = ${JSON.stringify(results, null, 2)}

/**
 * Returns the pre-computed AnalysisResult for a flow text if (and only if)
 * the text matches one of the built-in samples exactly. Returns null otherwise
 * so the caller falls through to the live API.
 */
export function getSampleResult(flowText: string): AnalysisResult | null {
  const trimmed = flowText.trim()
  for (const [label, text] of Object.entries(SAMPLE_FLOWS)) {
    if (text.trim() === trimmed) {
      return SAMPLE_RESULTS[label] ?? null
    }
  }
  return null
}
`

writeFileSync(join(projectRoot, 'src/lib/sample-results.ts'), output)
console.log('\nWrote src/lib/sample-results.ts')
